name: Git Checkout
on: [push]
jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - name: List before
        run: ls -a
      - name: Checkout
        run: |
          git init
          git remote add origin "https://$GITHUB_ACTOR:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY.git"
          git fetch origin
          git checkout new-branch
      - name: List After
        run: ls -a