name: events
on: 
    pull_request: 
        types: [closed]
    issues: 
        types: [closed]


jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - run: |
            echo $GITHUB_SHA
            echo $GITHUB_REF
      - uses: actions/checkout@v3