name: First Workflow
on: [push]

jobs:
    first-workflow:
        runs-on: ubuntu-latest
        steps:
          - name: Error Message
            run: echo "::notice::Warning Message"
          - name: Group message
            run: echo "::group::Group Title"
                echo "Inside Group 1"
                echo "Inside Group 2"
                 echo "::endgroup::"