name: first-workflow
on: push

jobs:
  first-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: first-step
        run: echo "Hello World"
      - name: second-step
        run: | 
          echo "Node Version"
          node -v
          echo "NPM Version"
          npm -v
          echo "Python Version"
          python -V