name: Working Directory and shells
on: [push]
jobs:
    Working-dir:
        runs-on: ubuntu-latest
        steps:
            - name: Working dir
              run: |
                pwd
                ls -a
                echo "$GITHUB_SHA"
                echo "$GITHUB_REPOSITORY"
                echo "$GITHUB_WORKSPACE"
    Working-dir-windows:
        runs-on: windows-latest
        steps:
            - name: Working dir
              run: |
                Get-Location
                dir
                echo "$env:GITHUB_SHA"
                echo "$env:GITHUB_REPOSITORY"
                echo "$env:GITHUB_WORKSPACE"
            - name: Python test
              shell: python
              run: |
                import platform
                print(platform.processor())